import sys
import os
import json
import tempfile
import requests
from PyQt6.QtWidgets import (QApplication, QMainWindow, QWidget, QVBoxLayout,
                             QHBoxLayout, QPushButton, QLabel, QStackedWidget,
                             QListWidget, QMessageBox)
from PyQt6.QtCore import (Qt, QUrl, pyqtSignal, pyqtProperty,
                          QPropertyAnimation, QEasingCurve)
from PyQt6.QtMultimedia import QMediaPlayer, QAudioOutput
from PyQt6.QtGui import (QFont, QPainter, QTransform, QPen, QColor, QTextOption)

FLASHCARDS_DIR = "FlashcardUploads"
ELEVENLABS_API_KEY = "YOUR_API_KEY_HERE"  # Replace with actual ElevenLabs API key

class FlashcardWidget(QWidget):
    clicked = pyqtSignal()
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self.text = ""
        self._rotation_y = 0.0

        # Animation setup inspired by Animista's flip-in-ver-left
        # /* ----------------------------------------------
        #  * Generated by Animista on 2026-3-7 12:59:23
        #  * Licensed under FreeBSD License.
        #  * See http://animista.net/license for more info. 
        #  * w: http://animista.net, t: @cssanimista
        #  * ---------------------------------------------- */
        self.anim = QPropertyAnimation(self, b"rotationY")
        
        # We split the 500ms animista animation into two halves (250ms each)
        self.anim.setDuration(250) 
        self.anim.setEasingCurve(QEasingCurve.Type.InOutQuad)
        
        self.anim.finished.connect(self._on_anim_finished)
        self._is_animating_out = False
        self._next_text = ""

    @pyqtProperty(float)
    def rotationY(self):
        return self._rotation_y
        
    @rotationY.setter
    def rotationY(self, value):
        self._rotation_y = value
        self.update()
        
    def setText(self, text):
        self.text = text
        self.update()

    def flip_to_text(self, text):
        if text == self.text:
            return
        self._next_text = text
        self._is_animating_out = True
        
        # Animista: 0% rotateY(80deg) to 100% rotateY(0)
        # To simulate a full flip, we first animate OUT from 0 to 80
        self.anim.setStartValue(0.0)
        self.anim.setEndValue(80.0)
        self.anim.start()
        
    def _on_anim_finished(self):
        if self._is_animating_out:
            # Swap text exactly when the card edge is facing the user (80 deg)
            self.text = self._next_text
            self._is_animating_out = False
            
            # Now animate IN from 80 to 0 (This is the Animista flip-in-ver-left CSS)
            self.anim.setStartValue(80.0)
            self.anim.setEndValue(0.0)
            self.anim.start()

    def mousePressEvent(self, event):
        if event.button() == Qt.MouseButton.LeftButton:
            self.clicked.emit()
            
    def paintEvent(self, event):
        painter = QPainter(self)
        painter.setRenderHint(QPainter.RenderHint.Antialiasing)
        
        transform = QTransform()
        
        # Move origin to center of widget
        cw = self.width() / 2.0
        ch = self.height() / 2.0
        
        transform.translate(cw, ch)
        # Apply 3D rotation with the 3rd argument as distanceToPlane for perspective projection
        transform.rotate(self._rotation_y, Qt.Axis.YAxis, 800.0)
        transform.translate(-cw, -ch)
        
        painter.setTransform(transform)
        
        # Draw card background
        rect = self.rect().adjusted(10, 10, -10, -10)
        
        painter.setPen(QPen(QColor("#ccc"), 2))
        painter.setBrush(QColor("white"))
        painter.drawRoundedRect(rect, 10, 10)
        
        # Draw text
        painter.setPen(QColor("black"))
        font = QFont("Arial", 24)
        painter.setFont(font)
        
        text_option = QTextOption(Qt.AlignmentFlag.AlignCenter)
        text_option.setWrapMode(QTextOption.WrapMode.WordWrap)
        
        from PyQt6.QtCore import QRectF
        painter.drawText(QRectF(rect.adjusted(20, 20, -20, -20)), self.text, text_option)


class FlashcardApp(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Flashcard Study Tool")
        self.resize(600, 400)

        self.flashcards = []
        self.current_card_index = 0
        self.is_front = True

        # Setup Audio
        self.player = QMediaPlayer()
        self.audio_output = QAudioOutput()
        self.player.setAudioOutput(self.audio_output)
        self.temp_audio_file = None

        # Main Layout
        self.stacked_widget = QStackedWidget()
        self.setCentralWidget(self.stacked_widget)

        self.init_pages()
        self.load_folders()

    def init_pages(self):
        # 0: Selection Page
        self.selection_page = QWidget()
        self.selection_layout = QVBoxLayout(self.selection_page)
        
        self.title_label = QLabel("Select a Flashcard Deck to Study")
        self.title_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.title_label.setFont(QFont("Arial", 16, QFont.Weight.Bold))
        self.selection_layout.addWidget(self.title_label)
        
        self.deck_list = QListWidget()
        self.deck_list.itemClicked.connect(self.start_flashcards)
        self.selection_layout.addWidget(self.deck_list)

        # Buttons on selection page
        btn_layout = QHBoxLayout()
        self.add_deck_btn = QPushButton("+ Create New / Import Flashcards")
        self.add_deck_btn.clicked.connect(self.go_to_import)
        btn_layout.addWidget(self.add_deck_btn)
        self.selection_layout.addLayout(btn_layout)

        # 1: Flashcard Learn Page
        self.learn_page = QWidget()
        self.learn_layout = QVBoxLayout(self.learn_page)
        
        self.card_widget = FlashcardWidget()
        self.card_widget.clicked.connect(self.flip_card)
        self.learn_layout.addWidget(self.card_widget, stretch=1)

        control_layout = QHBoxLayout()
        self.flip_btn = QPushButton("Flip")
        self.flip_btn.clicked.connect(self.flip_card)
        self.read_btn = QPushButton("Read Aloud")
        self.read_btn.clicked.connect(self.read_aloud)
        self.next_btn = QPushButton("Next")
        self.next_btn.clicked.connect(self.next_card)

        control_layout.addWidget(self.flip_btn)
        control_layout.addWidget(self.read_btn)
        control_layout.addWidget(self.next_btn)

        self.learn_layout.addLayout(control_layout)

        # 2: Import Shortcut Dud Page
        self.import_page = QWidget()
        import_layout = QVBoxLayout(self.import_page)
        import_label = QLabel("[DUD] Import Flashcards Page")
        import_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        import_label.setFont(QFont("Arial", 16))
        import_back_btn = QPushButton("Back")
        import_back_btn.clicked.connect(lambda: self.stacked_widget.setCurrentIndex(0))
        import_layout.addWidget(import_label)
        import_layout.addWidget(import_back_btn)

        # 3: End of Stack Page
        self.end_page = QWidget()
        end_layout = QVBoxLayout(self.end_page)
        end_label = QLabel("You have reached the end of this deck!")
        end_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        end_label.setFont(QFont("Arial", 16))
        
        play_btn = QPushButton("Play a Game")
        play_btn.clicked.connect(lambda: QMessageBox.information(self, "Dud", "Play a game feature coming soon!"))
        
        continue_btn = QPushButton("Continue Learning")
        continue_btn.clicked.connect(lambda: self.stacked_widget.setCurrentIndex(0))

        quit_btn = QPushButton("Quit to Title Screen")
        quit_btn.clicked.connect(lambda: QMessageBox.information(self, "Dud", "Quit to Title Screen feature coming soon!"))

        end_layout.addWidget(end_label)
        end_layout.addWidget(play_btn)
        end_layout.addWidget(continue_btn)
        end_layout.addWidget(quit_btn)

        # Add pages to stacked widget
        self.stacked_widget.addWidget(self.selection_page)  # Index 0
        self.stacked_widget.addWidget(self.learn_page)      # Index 1
        self.stacked_widget.addWidget(self.import_page)     # Index 2
        self.stacked_widget.addWidget(self.end_page)        # Index 3

    def load_folders(self):
        self.deck_list.clear()
        if not os.path.exists(FLASHCARDS_DIR):
            os.makedirs(FLASHCARDS_DIR)

        files = [f for f in os.listdir(FLASHCARDS_DIR) if f.endswith('.json')]
        if not files:
            QMessageBox.information(self, "No Decks", "You do not have any flashcard folders. Please create one.")
            self.go_to_import()
        else:
            for file in files:
                self.deck_list.addItem(file)

    def go_to_import(self):
        self.stacked_widget.setCurrentIndex(2)

    def start_flashcards(self, item):
        filename = item.text()
        filepath = os.path.join(FLASHCARDS_DIR, filename)
        print(f"DEBUG: Selected item: {filename}")
        print(f"DEBUG: Filepath is: {filepath}")
        
        try:
            print("DEBUG: Loading JSON...")
            with open(filepath, 'r', encoding='utf-8') as f:
                self.flashcards = json.load(f)
            print(f"DEBUG: JSON loaded successfully. Found {len(self.flashcards)} cards.")
        except Exception as e:
            print(f"DEBUG: Exception during loading JSON: {e}")
            QMessageBox.critical(self, "Error", f"Failed to load JSON:\n{str(e)}")
            return

        if not self.flashcards:
            print("DEBUG: The deck is empty.")
            QMessageBox.warning(self, "Empty Deck", "This deck has no flashcards.")
            return

        print("DEBUG: Initializing card index and flipping states.")
        self.current_card_index = 0
        self.is_front = True
        print("DEBUG: Calling update_card_display...")
        self.update_card_display(animate=False)
        print("DEBUG: Setting current stacked widget index to 1.")
        self.stacked_widget.setCurrentIndex(1)
        print("DEBUG: start_flashcards finished successfully.")

    def update_card_display(self, animate=True):
        print(f"DEBUG: update_card_display called with animate={animate}")
        card = self.flashcards[self.current_card_index]
        text = card.get("term", "") if self.is_front else card.get("answer", "")
        print(f"DEBUG: Retrieved text to display: '{text}' (is_front: {self.is_front})")
        
        if animate:
            print("DEBUG: Calling self.card_widget.flip_to_text...")
            self.card_widget.flip_to_text(text)
        else:
            print("DEBUG: Calling self.card_widget.setText...")
            self.card_widget.setText(text)
        print("DEBUG: update_card_display finished.")

    def flip_card(self):
        self.is_front = not self.is_front
        self.update_card_display(animate=True)

    def next_card(self):
        self.current_card_index += 1
        if self.current_card_index >= len(self.flashcards):
            self.stacked_widget.setCurrentIndex(3)
        else:
            self.is_front = True
            self.update_card_display(animate=False)

    def read_aloud(self):
        if ELEVENLABS_API_KEY == "YOUR_API_KEY_HERE":
            QMessageBox.information(self, "API Key Required", "Set ELEVENLABS_API_KEY to use this feature.")
            return

        card = self.flashcards[self.current_card_index]
        text = card.get("term", "") if self.is_front else card.get("answer", "")

        url = "https://api.elevenlabs.io/v1/text-to-speech/21m00Tcm4TlvDq8ikWAM"
        headers = {
            "Accept": "audio/mpeg",
            "Content-Type": "application/json",
            "xi-api-key": ELEVENLABS_API_KEY
        }
        data = {
            "text": text,
            "model_id": "eleven_monolingual_v1",
            "voice_settings": {
                "stability": 0.5,
                "similarity_boost": 0.5
            }
        }
        
        try:
            response = requests.post(url, json=data, headers=headers)
            if response.status_code == 200:
                fd, path = tempfile.mkstemp(suffix=".mp3")
                with os.fdopen(fd, 'wb') as f:
                    f.write(response.content)
                self.temp_audio_file = path
                
                self.player.setSource(QUrl.fromLocalFile(path))
                self.player.play()
            else:
                QMessageBox.warning(self, "API Error", f"ElevenLabs API Error: {response.text}")
        except Exception as e:
            QMessageBox.critical(self, "Error", f"Failed to connect to ElevenLabs API:\n{str(e)}")

    def closeEvent(self, event):
        if self.temp_audio_file and os.path.exists(self.temp_audio_file):
            try:
                os.remove(self.temp_audio_file)
            except:
                pass
        super().closeEvent(event)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    window = FlashcardApp()
    window.show()
    sys.exit(app.exec())
